version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: rails_app
      POSTGRES_PASSWORD: rails_app
      POSTGRES_DB: rails_app_development
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: rails_app
      POSTGRES_PASSWORD: rails_app
      DB_HOST: db
    volumes:
      - .:/rails_app
    ports:
      - "80:80"
    depends_on:
      - db